openapi: 3.0.3
info:
  title: API ecomm-order
  description: API para acessar os pedidos do e-commerce
  version: 0.0.1
paths:
  /api/orders:
    post:
      tags:
      - Pedidos
      summary: Faz um novo pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
  /api/orders{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    get:
      tags:
      - Pedidos
      summary: Lista detalhes de um pedido
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        404:
          description: Pedido não encontrado
          content:
            application/json:
              schema:
                example: "Não encontrado"                          
components:
  schemas:
    Order:
      type: object
      properties:
        idCliente:
          type: string
        enderecoEntrega:
          type: object
          properties:
            rua:
              type: string
            numero:
              type: string
            complemento:
              type: string
            cep:
              type: string
            cidade:
              type: string
            estado: 
              type: string
        itens:
          type: array
          items:
            type: object
            properties:
              id: 
                type: string
              quantidade:
                type: integer
              valorDesconto:
                type: number
                format: double
              precoUnitario:
                type: number
                format: double              