version: "3.9"
services: 
  product: 
    build: ./product
    container_name: ecomm-product
    ports:
      - ${PRODUCT_PORT}:${PRODUCT_PORT}
    depends_on:
      - mongodb
      - redis
  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    depends_on:
      - mongodb
      - redis
  finance:
    build: ./finance
    container_name: ecomm-finance
    ports:
      - ${FINANCE_PORT}:${FINANCE_PORT}
    depends_on:
      - mysql
      - redis
  order:
    build: ./order
    container_name: ecomm-order
    ports: 
      - ${ORDER_PORT}:${ORDER_PORT}
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: mongo-ecomm
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    env_file:
      - ./product/.env
    volumes:
      - ecomm-mongo:/data/db
  mysql:
    image: mysql
    container_name: mysql-ecomm
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - ./.env
    volumes:
     - ecomm-mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: redis-ecomm
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ecomm-redis:/data

volumes: 
  ecomm-mysql:
  ecomm-mongo:
  ecomm-redis: