openapi: 3.0.3
info:
  title: API ecomm-product
  description: API para acessar as categorias e produtos do e-commerce
  version: 0.0.1
paths:
  /api/categories:
    get:
      tags:
        - Categorias
      summary: Acessa todas categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /api/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    get:
      tags:
      - Categorias
      summary: Lista detalhes de uma categoria
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Não encontrado"                 
  /api/admin/categories:
    post:
      tags: 
      - Categorias
      summary: Cadastra novas categorias (admin)
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              type: object
              properties:
                nome: 
                  type: string
      responses:
        201:
          description: Adicionado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /api/admin/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    put:
      tags:
      - Categorias
      summary: Atualiza uma categoria (admin)
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: Atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category' 
        404:
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                example: "Não encontrado"               
    delete:
      tags:
      - Categorias
      summary: Remove uma categoria (admin)
      responses:
        200: 
          description: Deletado com sucesso
        404:
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                example: "Não encontrado"          
    patch:
      tags:
      - Categorias
      summary: Ativa uma categoria (admin)
      responses:
        200:
          description: Ativado com sucesso
        404:
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                example: "Não encontrado"          
  /api/products:
    parameters:
    - in: query
      name: preco
      required: false
      schema:
        type: number
        format: double
    - in: query
      name: categoria
      required: false
      schema:
        type: string
    - in: query
      name: estoque
      required: false
      schema:
        type: integer  
    get:
      summary: Acessa todos produtos
      tags:
      - Produtos
      responses: 
        200: 
          description: Sucesso
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Products"
        400:
          description: Parâmetros inválidos
          content:
            appliction/json:
              schema:
                example: "Parâmetros incorretos"                  
  /api/products/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    get:
      tags:
      - Produtos
      summary: Lista detalhes de um produto
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Produto não encontrado
          content:
            application/json:
              example: "Não encontrado"      
  /api/admin/products:
    post:
      summary: Adiciona um novo produto (admin)
      tags:
      - Produtos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome: 
                  type: string
                descricao:
                  type: string
                slug:
                  type: string
                precoUnitario:
                  type: number
                  format: double
                quantidadeEmEstoque:
                  type: integer
                idCategoria:
                  type: string
      responses:
        201:
          description: Adicionado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
  /api/admin/products/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    put:
      tags:
      - Produtos
      summary: Atualiza um produto (admin)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome: 
                  type: string
                descricao:
                  type: string
                slug:
                  type: string
                precoUnitario:
                  type: number
                  format: double
                quantidadeEmEstoque:
                  type: integer
                idCategoria:
                  type: string
      responses:
        200:
          description: Atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Produto não encontrado
          content:
            application/json:
              example: "Nâo encontrado"
    delete:
      tags:
      - Produtos
      summary: Deleta um produto (admin)
      responses:
        200:
          description: Produto deletado
        404:
          description: Produto não encontrado
          content:
            application/json:
              example: "Não encontrado"          
components:
  schemas:
    Category:
        type: object
        properties:
          id:
            type: string
          nome:
            type: string
          status:
            type: string
    Product:
      type: object
      properties:
        id: 
          type: string
        produto: 
          type: string
        descricao: 
          type: string
        slug: 
          type: string
        precoUnitario: 
          type: number
          format: double
        quantidadeEmEstoque: 
          type: integer
        categoria:
          type: object
          properties:
            id:
              type: string
            nome:
              type: string
    Products:
      type: array
      items:
        type: object
        properties:
          id: 
            type: string
          produto:
            type: string