openapi: 3.0.3
info:
  title: API ecomm-alura
  description: API para acessar as categorias e produtos do e-commerce
  version: 0.0.1
  
paths:
  /api/categories:
    get:
      tags:
        - Categorias
      summary: Acessa todas categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
