openapi: 3.0.3
info:
  title: API ecomm-alura
  description: API para acessar as categorias e produtos do e-commerce
  version: 0.0.1
  
paths:
  /api/categories:
    get:
      tags:
        - Categorias
      summary: Acessa todas categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /api/admin/categories:
    post:
      tags: 
      - Categorias
      summary: Cadastra novas categorias
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              properties:
                nome: 
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
components:
  schemas:
    Category:
        type: object
        properties:
          _id:
            type: string
          nome:
            type: string
          status:
            type: string
